language: perl
sudo: false
perl:
- '5.30'
- '5.28'
- '5.26'
- '5.24'
- '5.22'
- '5.20'
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
- '5.8'

# before_install:
# - git clone git://github.com/travis-perl/helpers
#   ~/travis-perl-helpers
# - source ~/travis-perl-helpers/init --auto

install:
  - perlbrew install-cpanm -f
  - cpanm --quiet --notest
      Test::Base
      JSON::PP
      boolean
      JSON::XS

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
